services:
  postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: "keycloak"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1"
        ports:
            - "5432:5432"
        networks:
            - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: "1"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
       - keycloak_network
networks:
  keycloak_network:
    driver: bridge