spring:
  application:
    name: arena-api
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pokemon
  r2dbc:
    username: "postgres"
    password: "1"
    name: "pokemon"
    url: r2dbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8002
