openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8000/v1
paths:
  /pokemon:
    get:
      summary: list all available pokemons
      operationId: listPokemons
      description: List all available pokemons
      responses:
        '200':
          description: A paged array of pokemons
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pokemons"
    post:
      summary: saves a pokemon
      operationId: savePokemon
      description: Saves a pokemon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PokemonDto"
      responses:
        '200':
          description: Pokemon was successfully saved
          content:
            application/json:
              schema:
                type: integer
                format: int64
  '/pokemon/{pokemonId}':
    get:
      summary: Find pokemon by id
      operationId: findPokemonById
      description: Returns pokemon with given id
      parameters:
        - name: pokemonId
          in: path
          description: ID of pokemon to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A paged array of pokemons
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PokemonDto"
        '400':
          description: Invalid id
        '404':
          description: Pokemon not found

components:
  schemas:
    PokemonDto:
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
    Pokemons:
      type: array
      items:
        $ref: "#/components/schemas/PokemonDto"
